### ISSUE TITLE
Simple OTA updates node + js + native dependencies.

### ISSUE THREAD

**Issue by lightsofapollo** [mozilla-iot/gateway#167]
We need a rapid way to release our code in a very generic way. This should be a simple solution that does not address things like updating the whole system image. 

Requirements:
 
 - [ ] A/B deployments : We can update (untar/unzip a folder) while the device is running and gracefully boot into the update (falling back if we fail to start).
 - [ ] Publish javascript + sourcemap to GH so we can download them for update.
 - [ ] Can ship javascript dependencies with sourcemaps 
 - [ ] Can ship native dependencies (openzwave)
 - [ ] Can ship node versions (i.e. update from 7.7 to 7.8, etc..).

**Comment by lightsofapollo** [comment]
I created the prerequisite S3 buckets and documented their usage here: https://github.com/mozilla-iot/wiki/wiki/S3-Buckets-and-their-purpose.

**Comment by hobinjk** [comment]
- Cron job querying GitHub releases API
- Releases contain both gateway-HASH.tar.gz and node_modules-HASH.tar.gz
- Script unpacks both into new directory
- Copies database and settings
- Somehow checks that it runs (running Jest is a possibility but overkill)
- At this point the new gateway is started on 8081, 4444 and the iptables rules are switched over
- If the new gateway crashes/errors, the iptables get switched back
`node_modules` generation scripts are [create](https://github.com/hobinjk/gateway/blob/archive-node_modules/tools/create-node_modules-archive.sh) and [extract](https://github.com/hobinjk/gateway/blob/archive-node_modules/tools/extract-node_modules-archive.sh). This can also be generalized to the gateway archive

**Comment by dhylands** [comment]
I'm not quite sure of the benefit of using 2 different sets of ports? In general, you can't run 2 copies of the gateway at the same time. Things like serial ports will be exclusively opened by one instance and the second instance will fail (or at the very least should fail) to open the ports.

So I think that we should shut down one instance of the gateway - which is probably required to ensure database consistency as well) and then startup the new instance.

**Comment by hobinjk** [comment]
Good point! I set upon the idea of two sets of ports as a neat way to do instantaneous failover but I hadn't thought of the potential for issues around the two gateways contesting unshareable resources. I'll edit my comment to use your better (and simpler) proposal.

**Comment by hobinjk** [comment]
- Cron job querying GitHub releases API
- If releases tag is a semantic version greater than the current version of the gateway in package.json, then download the release
- Releases contain both gateway-HASH.tar.gz and node_modules-HASH.tar.gz
- Script unpacks both into new directory
- Copies database and settings if required by the offline check (next step)
- Somehow checks that the new gateway runs (running Jest is a possibility but overkill)
- Gracefully shutdown the old gateway
- Copy database and settings again
- Start the new gateway
- If the new gateway crashes/errors, shut it down, start the old gateway, and go back to the first step

**Comment by hobinjk** [comment]
My initial thought for a heuristic representing the "errors" in "crashes/errors" is just if there's an unhandled promise rejection. It would be interesting to do something like "if there are more than 10 console.error calls in a minute," but I think this sort of rate-based heuristic would mostly lead to inexplicable update failures.

I believe the new gateway should be under the threat of rollback until a higher version exists which is predicated upon our current 2-week release schedule. If we end up releasing at a slower cadence, I think 2 weeks is still a mostly reasonable threshold for permanently moving on from the old gateway version.

**Comment by hobinjk** [comment]
An additional thought I had that I would like to note is that it will likely be necessary at some point to run database migrations. I'd like to introduce a no-op script in package.json called `postupgrade` or `migrate` that so that we have a designated place to put that potentially meddlesome logic.

What I think will be the fun part of migrating is that we'll need to keep track of the database version (hopefully in the database) to track whether reverting to the old gateway will require reverting to the old database. The same goes for the node-persist settings.

**Comment by dhylands** [comment]
I think that the database and node-persist stuff probably belongs inside the A/B directory structure, so that when you rollback to a previous version you automatically roll-back the db/settings.

**Comment by hobinjk** [comment]
That's certainly safer. It definitely makes sense to not try to be clever for this first stab at OTA.

**Comment by benfrancis** [comment]
@hobinjk The initial implementation of this is done now, right? Should we close this?

**Comment by hobinjk** [comment]
@benfrancis Yes, but I think there should be follow-up issues for the two things we haven't done:
- Can ship native dependencies (openzwave)
- Can ship node versions (i.e. update from 7.7 to 7.8, etc..).

**Comment by mrstegeman** [comment]
These remaining tasks can now be done via the post-upgrade script.
