### ISSUE TITLE
Adapter/Client API

### ISSUE THREAD

**Issue by lightsofapollo** [mozilla-iot/gateway#169]
Ship the ability to automatically generate client APIs which are flexible enough to serve multiple use cases in the near future (IPC, Java SDK,  Server SDK).

Requirements:

 - [ ]  Server uses [OpenAPI](https://www.openapis.org/) to define input and outputs (at minimum for REST interactions over HTTP 1/2) and validates both.
 - [ ] Auto generate scaffolding for JS clients.
 - [ ] Auto generate very basic documentation for JS clients.
 - [ ] Implement the simple JWT authentication mechanism for auth we now require.
