### ISSUE TITLE
Things adapter ecosystem basics (testing / tools / examples).

### ISSUE THREAD

**Issue by lightsofapollo** [mozilla-iot/gateway#170]
We need to take some basic incremental steps to make our adapter API look like something that belongs in the NPM ecosystem (as a simple start). This will help us solicit external feedback and eventually lead to doing more complex things like IPC/Capabilities based security models.

Requirements:

 - [ ] Define V1 API for creating adapters in JS (npm packages)
 - [ ] Implement facade for the future IPC mechanism. All communication still happens in process but we serialize all data and use asynchronous APIs (i.e. look closely like it should once we have completed our IPC goals).
 - [ ] Ship an adapter to the npm ecosystem and collaborate with outside parties to get feedback.
 - [ ] Define tooling we need to test various types of adapters and how we would also provide that to our ecosystem.

Depends on https://github.com/mozilla-iot/gateway/issues/169 for the generation of the client API.

**Comment by lightsofapollo** [comment]
"Ship an adapter to the npm ecosystem and collaborate with outside parties to get feedback."

@kgrandon (external contributor) and @dmarcos (mozilla on WebVR) are willing to be our sounding board here.

**Comment by mrstegeman** [comment]
We've got a good amount of documentation, blog posts, and examples available now.
