### ISSUE TITLE
Rules Engine

### ISSUE THREAD

**Issue by lightsofapollo** [mozilla-iot/gateway#172]
We want to have an offline version of a rules engine (think if then that that perhaps?). Part of this issue is finding a useful demonstrable use case.

- [ ] Level-based triggers on number properties
- [ ] Value triggers on booleans
- [ ] "set" action which permanently changes the value of a property
- [ ] "pulse" action which changes a property only when it is in a triggered state
- [ ] Create a UI for managing rules
 - [ ] Define one use case as an example for the overall ecosystem.

**Comment by igilham** [comment]
As far as use cases go, one of the weaknesses of many IoT platforms is that web connections are unreliable, and many platforms simply break when not connected to their Vendor's server-side infrastructure. Consider if you set up a rule to trigger a siren when a door opens while you're away from home. An online-only system will fail to raise the alarm.

**Comment by hobinjk** [comment]
The main components required for an IFTTT-esque rules engine are triggers and actions. The ones that we care about right now operate on the properties of Web Things. Triggers will listen to property values then call whichever action they have associated. For now, actions will either set or pulse a property. Scaling likely won't be an issue as everything will run locally

- [ ] Level-based triggers on number properties
- [ ] Value triggers on booleans
- [ ] "set" action which permanently changes the value of a property
- [ ] "pulse" action which changes a property only when it is in a triggered state

Future work is creating internet-connected triggers and actions and supporting local logic (delay 5 seconds, numerical and boolean operations, time-based triggers)

**Comment by lightsofapollo** [comment]
@hobinjk Correct me if I am wrong but this seems like the perfect type of problem to sit on top of our websocket api (as a consumer) rather than directly in the gateway implementation ?

**Comment by hobinjk** [comment]
@lightsofapollo Yes, the idea is to have it run completely separately as an example of what's possible with the API.

**Comment by benfrancis** [comment]
Moved to https://github.com/mozilla-iot/rules-engine/issues
