### ISSUE TITLE
Android Things Web Things library/example

### ISSUE THREAD

**Issue by lightsofapollo** [mozilla-iot/gateway#174]
We wish to demonstrate our capability to query/modify/integrate /w existing off the shelf android things via our API(s) .

## Requirements:

 - [ ] Integrate with an existing off the shelf android things (we need to find one that is a suitable candidate) to expose querying the device (like a sensor or thermostat)  .
 - [ ] Build an example (or common scaffolding) for the wider ecosystem.
 - [ ] Solicit feedback from at least one external party with experience building for Android.
 
 Depends on https://github.com/mozilla-iot/gateway/issues/169 for the generation of the client API.

**Comment by igilham** [comment]
While we do need more device examples, it may be easiest to start with a few virtual devices that can demonstrate basic Thing types without the burden of hardware testing.

**Comment by lightsofapollo** [comment]
@igilham What would be most useful to you ? We are still working on prioritizes.

**Comment by igilham** [comment]
@lightsofapollo Probably just a simple button or binarySensor that can be manually toggled as a trigger and a switch like the already supported Aotech switch. Having a few basic examples should inform the design of the rules engine as it will make it easier to play with different integration scenarios.

**Comment by benfrancis** [comment]
Moved to https://github.com/mozilla-iot/webthing-java/issues
