### ISSUE TITLE
Issue spoken commands to the gateway using speech api and the intent parser Rest API

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway#266]

**Comment by andrenatal** [comment]
- [ ] Integrate Mozilla STT API: https://github.com/mozilla-iot/gateway/issues/262
- [ ] Implement voice level animation: https://github.com/mozilla-iot/gateway/issues/271
- [ ] Integrate intent REST API: https://github.com/mozilla-iot/gateway/issues/261
- [ ] Implement toast notifications to notify failure and success
- [ ] Implement sound notifications to notify failure and success

**Comment by andrenatal** [comment]
Closed by #290
