### ISSUE TITLE
Support OAuthv2 as a Server

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#305]
As a developer, I want to write third-party Gateway apps that use OAuthv2 to enable users to securely grant access to them. Users will open my app and get redirected to the gateway which will prompt them to allow my app access to a defined set of capabilities on their Things.

This has the secondary benefit of requiring our JWT authentication system to support expiration, renewal, and scopes which reduces the severity of potential credential-stealing attacks on the gateway.

Initial implementation:
- [x] [Authorization flow](https://github.com/mozilla-iot/gateway/issues/335)
- [x] [List active authorizations](https://github.com/mozilla-iot/gateway/issues/336)
- [x] [Issue authorization grants](https://github.com/mozilla-iot/gateway/issues/339)

Enhancements:
- [ ] [Support scoping JWTs to Thing sets](https://github.com/mozilla-iot/gateway/issues/337)
- [ ] [Support scoping JWTs to read/write access](https://github.com/mozilla-iot/gateway/issues/338)
- [ ] [Third-party registration](https://github.com/mozilla-iot/gateway/issues/340)
